"""
Django settings for hwmsOffice project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%&r0adqr@r$ogia$0rhte6vy!8&#w)4e=vqom53!65y*c9-rj_'

# SECURITY WARING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

BATON = {
    'SITE_HEDER': 'HWMS 백오피스',
    'SITE_TITLE': 'HWMS 백오피스',
    'INDEX_TITLE': 'HWMS 관리자페이지',
    # 'SUPPORT_HREF': 'https://tvstormvietnam.vn',
    'SUPPORT_HREF': 'mailto:yhryu102@gmail.com',
    'COPYRIGHT': 'copyright © 2020 TVStorm Vietnam Co., Ltd.',
    'POWERED_BY': '<a href="http://auraclinic.vn">AURA Clinic</a>',
    'MENU_TITLE': 'AURA Clnic',
    'MENU': (
        { 'type': 'title', 'label': 'main' },
        {
            'type': 'app',
            'name': 'cstmng',
            'label': '고객',
            'icon': 'fa fa-lock',
            'models': (
                {
                    'name': 'cstmng',
                    'label': '고객'
                },
            )
        },
        {
            'type': 'free', 'label': '예약', 'default_open': True, 'children': [
                { 'type': 'free', 'label': '예약', 'url': '/admin/rsvmng/rsvmng/' },
                { 'type': 'free', 'label': '예약 날짜 뷰', 'url': '/admin/rsvmng/rsvmng/date_view/' },
            ]
        },
        {
            'type': 'app',
            'name': 'goodsmng',
            'label': '상품',
            'models': (
                {
                    'name': 'goodsmng',
                    'label': '상품'
                },
            )
        },
        { 'type': 'free', 'label': '매뉴얼', 'url': '/admin/package' },
    ),
}

INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'grappelli.dashboard',
    # 'grappelli',

    'rest_framework',
    'adminactions',

    'hwmsuser.apps.UserConfig',
    'cstmng.apps.CstmngConfig',
    'goodsmng.apps.GoodsConfig',
    'rsvmng.apps.RsvmngConfig',
    'rangefilter',

    'baton.autodiscover',
]

# INSTALLED_APPS += [
#     'cstmng.apps.CstmngConfig',
#     'goodsmng.apps.GoodsConfig',
#     'rsvmng.apps.RsvmngConfig',
#     'rangefilter',
# ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hwmsOffice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hwmsOffice.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hwmsdb',
        'USER': 'root',
        'PASSWORD': '0817',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Django Admin / yyh
# GRAPPELLI_ADMIN_TITLE = 'Back Office'

# python manage.py customdashboard / yyh
# GRAPPELLI_INDEX_DASHBOARD = {
#     'django.contrib.admin.site': 'hwmsadmin.dashboard.CustomIndexDashboard',
# }

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# yyh - for logo inserting
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# MEDIA
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
