# Generated by Django 3.1.4 on 2021-01-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbSmmAuthorInfo',
            fields=[
                ('author_code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('author_nm', models.CharField(max_length=60)),
                ('author_dc', models.CharField(blank=True, max_length=1000, null=True)),
                ('spri_inner_author_at', models.IntegerField()),
                ('delete_at', models.IntegerField(blank=True, null=True)),
                ('dltr_sn', models.PositiveIntegerField(blank=True, null=True)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('frst_reg_ip', models.CharField(max_length=20)),
                ('frst_reg_dttm', models.DateTimeField()),
                ('frst_reg_id', models.CharField(max_length=20)),
                ('last_upd_ip', models.CharField(max_length=20)),
                ('last_upd_dttm', models.DateTimeField()),
                ('last_upd_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_smm_authorinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbSumUserInfo',
            fields=[
                ('user_sn', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='사용자번호')),
                ('user_nm', models.CharField(blank=True, max_length=60, null=True, verbose_name='이름')),
                ('user_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='직분')),
                ('user_se', models.CharField(blank=True, max_length=20, null=True)),
                ('work_branch', models.CharField(blank=True, choices=[('7Q', 'Fumyhung'), ('2Q', 'Branch-#2')], max_length=4, null=True, verbose_name='소속병원')),
                ('user_ty', models.CharField(blank=True, choices=[('DR', 'Doctor'), ('NU', 'Nulse'), ('SC', 'Skincare'), ('CD', 'Coordinator')], max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('company_nm', models.CharField(blank=True, max_length=60, null=True)),
                ('telno', models.CharField(blank=True, max_length=60, null=True, verbose_name='전화번호')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='이메일')),
                ('password', models.CharField(blank=True, max_length=60, null=True, verbose_name='패스워드')),
                ('new_password', models.CharField(blank=True, max_length=60, null=True)),
                ('stplat_agre_at', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('indvdlinfo_agre_at', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('indvdlinfo_agre_dt', models.DateTimeField(blank=True, null=True)),
                ('login_failr_co', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_login_dt', models.DateTimeField(blank=True, null=True)),
                ('back_last_login_dt', models.DateTimeField(blank=True, null=True)),
                ('secsn_at', models.CharField(blank=True, max_length=1, null=True)),
                ('secsn_dt', models.DateTimeField(blank=True, null=True)),
                ('lcns_no', models.CharField(blank=True, max_length=60, null=True)),
                ('zip', models.CharField(max_length=6)),
                ('bass_adres', models.CharField(max_length=100)),
                ('detail_adres', models.CharField(max_length=100)),
                ('brthdy', models.DateField(blank=True, null=True)),
                ('frst_reg_ip', models.CharField(max_length=20)),
                ('frst_reg_dttm', models.DateTimeField(auto_now_add=True)),
                ('frst_reg_id', models.CharField(max_length=20)),
                ('last_upd_ip', models.CharField(max_length=20)),
                ('last_upd_dttm', models.DateTimeField(auto_now_add=True)),
                ('last_upd_id', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '직원명단',
                'db_table': 'tb_sum_user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nm', models.CharField(max_length=60)),
                ('user_ty', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cats_photo/')),
            ],
        ),
    ]
